config/routes.rb
Rails.application.routes.draw do
  resources :ratings, only: [:create, :index, :update, :destroy]
  resources :movies, only: [:index]

  get '/login', to: 'sessions#new', as: :new_login
  get '/list', to: 'ratings#index'

  get '/watch/:id', to: 'movies#watch',  as: :watch
  get '/email',     to: 'users#email',   as: :email
  get '/lucky',     to: 'ratings#lucky', as: :lucky

  scope controller: :movies do 
    get '/error',     to: :error,  as: :error
    get '/about',     to: :about,  as: :about
    get '/reset',     to: :reset,  as: :reset
    get '/help',      to: :help,   as: :help 
  end

  get '/auth/:provider/callback', to: 'sessions#create'
  delete '/logout'  => 'sessions#destroy'

  root 'movies#index'

end

app/models/genre.rb
class Genre < ActiveRecord::Base
  has_many :movie_genres
  has_many :movies, through: :movie_genres
end

app/models/movie.rb
require 'open-uri'

class Movie < ActiveRecord::Base
  has_many :ratings
  has_many :users, through: :ratings
  has_many :movie_genres
  has_many :genres, through: :movie_genres

  def get_amazon_link
    doc = Nokogiri::HTML(open("http://www.imdb.com/title/#{self.imdb_id}"))
    if (!doc.css("div.watchbar2 a").empty?)
      "http://www.imdb.com" + doc.css("div.watchbar2 a").attr("href").value
    else
      nil
    end
  end

  def self.page_count
    result = JSON.parse(open("https://api.themoviedb.org/3/discover/movie?api_key=#{ENV['MOVIE_API']}&sort_by=vote_average.desc&vote_count.gte=15&vote_average.gte=7.5&page=1").read)
    return result["total_pages"]
  end

  def self.get_movie(page_count)
    random_num = rand(page_count) + 1
    result = JSON.parse(open("https://api.themoviedb.org/3/discover/movie?api_key=#{ENV['MOVIE_API']}&sort_by=vote_average.desc&vote_count.gte=15&vote_average.gte=7.5&page=#{random_num}").read)
    #refactor into two mehtods: get random page & get random movie from page)
    movie_id = result["results"].sample["id"]
    JSON.parse(open("https://api.themoviedb.org/3/movie/#{movie_id}?api_key=#{ENV['MOVIE_API']}&append_to_response=trailers").read)
  end

  def self.build_movie(result)
    #taking the first genre of the movie
    genres     = result["genres"]
    title      = result["title"]
    rating     = result["vote_average"]
    imdb_id    = result["imdb_id"]
    source_id  = result["trailers"]["youtube"][0]["source"]
    poster     = "http://image.tmdb.org/t/p/w500" + result["poster_path"]

    parameters = {title: title, rating: rating, imdb_id: imdb_id, source_id: source_id, poster: poster}

    movie = self.find_or_create(parameters)
    movie.build_genres(genres)
    movie
  end

  def build_genres(genres)
    genre_names = genres.map { |genre_hash| genre_hash["name"] }
    genre_names.each do |name|
      self.associate_or_create_genre(name)
    end
    self.save
  end

  def associate_or_create_genre(genre_name)
    self.associate_genre(genre_name) || self.genres.build(name: genre_name)
  end

  def associate_genre(genre_name)
     genre = Genre.find_by(name: genre_name)
     if genre
      genre.movies << self 
      genre.save
    else
      false
    end
  end

  def self.find_or_create(parameters)
    self.find_by(imdb_id: parameters[:imdb_id]) || self.create(parameters)
  end

  def self.pick_movie
    trailers = []
    movie = self.get_movie(page_count)
    while trailers.empty?
      movie = self.get_movie(page_count)
      trailers = movie["trailers"]["youtube"]
    end
    build_movie(movie)
  end
end

app/models/movie_genre.rb
class MovieGenre < ActiveRecord::Base
  belongs_to :movie
  belongs_to :genre
end

app/models/rating.rb
class Rating < ActiveRecord::Base
  belongs_to :user
  belongs_to :movie
  has_many   :genres, through: :movie
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :ratings
  has_many :movies, through: :ratings
  has_many :genres, through: :movies

  def self.login_from_omniauth(auth_hash)
    find_from_omniauth(auth_hash) || create_with_omniauth(auth_hash)    
  end

  def self.find_from_omniauth(auth_hash)
    find_by(:uid => auth_hash[:uid])
  end

  def self.create_with_omniauth(auth_hash)   
    create(:uid => auth_hash[:uid].to_i, :name => auth_hash[:info][:name], :email => auth_hash[:info][:email])
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :require_login, :set_client
 
  private

    def require_login
      unless logged_in?
        redirect_to new_login_path # halts request cycle
      end
    end

    def logged_in?
      !!current_user
    end
  
	  def log_in(user)
	    session[:user_id] = user.id
	  end

		def log_out
	    session.delete(:user_id)
      session.delete(:token)
      session.delete(:secret)
	    @current_user = nil
	  end

	  def current_user
		  @current_user ||= User.find_by(id: session[:user_id])
		end

    def set_client
      if logged_in?
        @client = create_client
      end
    end

    def create_client
      Twitter::REST::Client.new do |config|
        config.consumer_key        = ENV['TWITTER_KEY']
        config.consumer_secret     = ENV['TWITTER_SECRET']
        config.access_token        = session[:token]
        config.access_token_secret = session[:secret]
      end
    end
		helper_method :current_user

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController  
  def index
    @movie = Movie.pick_movie
    while @movie.users.include?(current_user)
      @movie = Movie.pick_movie
    end
  end

  def watch
  	@movie = Movie.find(params[:id])
  	@link = @movie.get_amazon_link
    if @link
      redirect_to @link
    else
      redirect_to error_path
    end
  end

  def error    
  end

  def help
  end

  def reset
    current_user.ratings.destroy_all
  end
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController

  before_action :get_ratings, only: [:index, :lucky]

  def create
    if !Rating.find_by(user_id:current_user.id, movie_id:params[:movie_id])
      Rating.create(user_id: current_user.id, movie_id: params[:movie_id], score: params[:score])    
      @movie = Movie.pick_movie
      while @movie.users.include?(current_user)
        @movie = Movie.pick_movie
      end
    end
  end

  def index
    @genres = @ratings_all.map {|movie| movie.genres}
    if !@genres.empty?
      #check if .uniq changes genres or they're already uniq
     @genres = @genres.flatten.uniq || @genres.flatten
     @genres.sort!{|a, b| a.name <=> b.name} 
    end
  end

  def update
  	@rating = Rating.find(params[:id])
  	@rating.watched = true
  	@rating.save
    @client.update("I just whatched #{@rating.movie.title} @WHATCHapp")
    
  end

  def destroy
  	@rating = Rating.find(params[:id])
  	@rating.destroy
 
  	render 'update.js.erb'
  end

  def lucky
    @choice = @ratings_all.sample
    @ratings_all.delete(@choice)
    while !@ratings_all.empty? && !@choice.movie.get_amazon_link
      @choice = @ratings_all.sample
      @ratings_all.delete(@choice)
    end
    if @choice
      redirect_to @choice.movie.get_amazon_link
    else
      redirect_to error_path
    end
  end

  private

    def get_ratings
      @ratings_yes = Rating.where(user_id: current_user.id, score: 2, watched: false)
      @ratings_maybe = Rating.where(user_id: current_user.id, score: 1, watched: false)
      @ratings_all = @ratings_yes + @ratings_maybe
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :require_login, only: [:create, :new]
  skip_before_action :set_client, only: [:create, :new, :destroy]

  def create
    @user = User.login_from_omniauth(auth_hash)
    log_in(@user)
    redirect_to '/'
  end

  def destroy
    log_out
    redirect_to root_url
  end

  protected

  def auth_hash
    info = request.env['omniauth.auth']
    session[:token] = info["credentials"]["token"]
    session[:secret] = info["credentials"]["secret"]
    info
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def email
    yes = Rating.where(user_id: current_user.id, score: 2, watched: false)
    maybe = Rating.where(user_id: current_user.id, score: 1, watched: false)
    ListMailer.list_email(params[:email],yes,maybe).deliver   
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application/_footer.html.erb
<div id="footer">
	<% if current_user %>
    <div id="title"><%= @movie.title %></div>
	  <div class="buttons">
	    <%= button_to 'No', ratings_path, params: {score: 0, movie_id: @movie.id}, remote: true, method: :post, class: "btn btn-default" %>
	    <%= button_to 'Maybe', ratings_path, params: {score: 1, movie_id: @movie.id}, remote: true, method: :post, class: "btn btn-default"%>
	    <%= button_to 'Yes', ratings_path, params: {score: 2, movie_id: @movie.id}, remote: true, method: :post, class: "btn btn-default" %>
	  </div>
	<% end %>
</div>

app/views/application/_listfooter.html.erb
<div id="list-footer">
   <%= form_tag(email_path, method: 'get', remote: true) do %>
     <%= text_field_tag(:email,nil,autocomplete: :off, placeholder: 'Email your list...') %>
     <%= submit_tag("Submit", id: 'ebutton') %>
   <% end %>
</div>

app/views/application/_nav.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top navbar-expanded">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">
                <img src=<%= image_path('logo3.png') %> class="img-responsive" alt="">
            </a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
                <li class="hidden">
                    <a href="#page-top"></a>
                </li>
                <li>
                    <%= link_to "Home", root_path %>
                </li>
                <li>
                    <%= link_to "About", about_path %>
                </li>
                <li>
                    <%= link_to 'My Movies', list_path, id: "my_movies" %>
                </li>
                <li>
                    <%= link_to "Help", help_path %>
                </li>
                <li>
                    <%= link_to "Log Out", logout_path, :method => :delete %>
                </li>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Whatch</title>
  <link href='https://fonts.googleapis.com/css?family=Raleway:700,900,400' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id = "background">
<div class="container">
  <% if current_user %>
	 <%= render 'nav' %>
  <% end %>
	<%= yield %>
</div>
</div>
</body>
</html>

app/views/movies/_movie.html.erb
<iframe width="100%" height="100%" src="//www.youtube.com/embed/<%= @movie.source_id %>?rel=0&autoplay=1&showinfo=0&controls=0&iv_load_policy=3" frameborder="0" allowfullscreen></iframe>

app/views/movies/about.html.erb
<br><br><br>

<h2>About Us</h2>
  <div class="panel panel-default">
    <div class="panel-heading">
      <h5>What is WHATCH?</h5>
      <hr class="colored help-colored">
      <span class="down" href="#about"><i class="fa fa-angle-down fa-fw"></i></span>
    </div>  
    <div class="panel-body">
     A tool that exposes the indecisive movie-watcher to popular and acclaimed movies through trailers.<br><br>
    </div>  

    <div class="panel-heading">
      <h5>About WHATCH</h5>
      <hr class="colored help-colored">
      <span class="down" href="#about"><i class="fa fa-angle-down fa-fw"></i></span>
    </div>
    <div class="panel-body">
      <div id="team">
        We are a team of movie lovers who believes no movie-watcher should have to struggle to find a great movie to watch. We agree that searching for films is frustrating, and inefficient. With a growing online selection of movie resources, how are we supposed to find movies to watch without searching through numerous websites?<br><br>

        As frustrated movie-finders, we envisioned a way to easily, and efficiently find popular movies personalized to our tastes. As excited developers, we found our inspiration for WHATCH: an application that combines our love of movies and the convenience of the internet to simplify the way we find great movies. WHATCH allows us to spend more time whatching and less time searching.<br><br>

        Our application combines the functionality of numerous online movie resources, such as IMDb and Amazon Instant Play, to ease the process of finding and selecting movies. WHATCH is efficient and fun&#8212; an  application of discovery and joy.<br><br>
      </div>
    </div>
    
    <div class="panel-heading">
      <h5>The Team</h5>
      <hr class="colored help-colored">
      <span class="down" href="#about"><i class="fa fa-angle-down fa-fw"></i></span>
    </div>
    <div class="panel-body">
      <%= image_tag('team.jpg', width: '50%') %><br><br>
      Amanda, Sara, and Jarret are students in the Ruby 006 class at <%= link_to("The Flatiron School", "http://flatironschool.com/" , target: "_blank") %>.<br><br>

      In her free time, <strong>Amanda</strong> enjoys doing theater and singing, and her next application will be a new version of WHATCH for cat videos on YouTube. <strong>Sara</strong> is a native New Yorker and pizza enthusiast. She plans on being Amanda's first 'Cat App' user. <strong>Jarret</strong> has a perennial thirst for knowledge and loves to figure out how things work. His hobbies are thinking about what his hobbies are. 
    </div>

    <div class="panel-heading">
      <h6>Credits</h6>
      <hr class="colored help-colored">
      <span class="down" href="#about"><i class="fa fa-angle-down fa-fw"></i></span>
    </div>
    <div class="panel-body">
      Thanks to <%= link_to("Ian Miller", "https://twitter.com/irmiller22" , target: "_blank") %>; we couldn't have done it without you!<br>
      Credit to Kyle Hayden for our awesome name: WHATCH.
    </div>  
  </div>

app/views/movies/error.html.erb
<header id="reel">
  <div class="brand-name">Sorry!</div>
  <hr class="colored">
  <div class="brand-name-subtext">We couldn't find your movie.</div>
</header>

app/views/movies/help.html.erb
<br><br><br>

<h2>How To Use Whatch</h2>
<div class="panel panel-default">
  <div class="panel-heading">
  <h5>Home Page</h5>
  <hr class="colored help-colored">
  <span class="down" href="#about"><i class="fa fa-angle-down fa-fw"></i></span>
  </div>
  <div class="panel-body">
    When logging into WHATCH, you will be redirected to your home page, which will automatically start a trailer for you.<br><br>
     As a user, you simply need to whatch the trailer and decide whether or not you wish to whatch that film in the future. To do this, just click on the 'Yes', 'Maybe', or 'No' buttons.<br><br>
      If you click on 'Yes' or 'Maybe' these films will be saved to your personalized movie list. To view your list of saved movies click on the 'My Movies' link in the navigation bar
  </div>
  <div class="panel-heading">
    <h5>My Movies Page</h5>
    <hr class="colored help-colored">
    <span class="down" href="#about"><i class="fa fa-angle-down fa-fw"></i></span>
  </div>
  <div class="panel-body">
    The My Movies page will list all movies that you have rated 'Yes' or 'Maybe'. You can sort these movies by your rating and by genre. Click on a movie's poster for more information about that movie!<br><br>

    Once you’ve whatched a movie, hover over the movie poster and click on the check button to remove the movie from your list and share with your followers on Twitter. To simply remove a movie from your list, hover over its poster and click on the ‘x’ button.<br><br>

    If you’re feeling lucky, click ‘WhatchMe’ for more information about a random movie!
  </div>
  <div class="panel-heading">
    <h5>Troubleshooting</h5>
    <hr class="colored help-colored">
    <span class="down" href="#about"><i class="fa fa-angle-down fa-fw"></i></span>
  </div>
  <div class="panel-body">
    If you are having any trouble with trailers or you simply want to remove all movies you have rated, click this: <br>
    <%= link_to button_tag("Reset", id: "resetMe"), reset_path, remote: :true %>
    <br>
     Warning: This will remove all movies form your list and add them back into the trailers queue for you to whatch.
  </div>
</div>

app/views/movies/index.html.erb
<!-- <h3> Welcome<% if current_user %>, <%= current_user.name %><% end %>! </h3>

<h2> <%= @movie.title %> </h2>  -->

<div id="trailer">
  <iframe width="100%" height="100%" src="//www.youtube.com/embed/<%= @movie.source_id %>?rel=0&autoplay=1&showinfo=0&controls=0&iv_load_policy=3" frameborder="0" allowfullscreen></iframe>
</div>

<%= render 'footer' %>

app/views/movies/reset.js.erb
$('#resetMe').blur();

app/views/ratings/_list.html.erb
<ul class="list-group">
<% ratings.each do |rating| %>
  <li class="list-group-item", data-id = <%= rating.id %>>
     <%= button_to '&#x2716'.html_safe, rating_path(rating),remote: true, method: :delete %>
     <%= link_to(rating.movie.title, watch_path(rating.movie), remote: true) %>
     <%= button_to '&#x2714'.html_safe, rating_path(rating), remote: true, method: :patch %>
  </li>
<% end %>
</ul>

app/views/ratings/_posters.html.erb
<% @ratings_all.each do |rating| %>
    <div class="portfolio <% if rating.score == 2 %>yes<% else %>maybe<% end %>
    <% rating.genres.each do |genre| %> <%= genre.name %> <% end %>" data-id="<%= rating.id %>" data-cat="" href="#portfolioModal1" data-toggle="modal">
        <div class="portfolio-wrapper">
            <%= link_to(image_tag(rating.movie.poster), watch_path(rating.movie), target: "_blank") %>
            <div class="caption">
                <div class="caption-text">
                    <span class="text-category">
                        <%= button_to '&#x2716'.html_safe, rating_path(rating),remote: true, method: :delete, class: "btn btn-default" %>
                        <%= button_to '&#x2714'.html_safe, rating_path(rating),remote: true, method: :patch, class: "btn btn-default" %>
                    </span>
                </div>
                <div class="caption-bg"></div>
            </div>
        </div>
    </div>
<% end %>

app/views/ratings/_rating.html.erb
<li>
  <%= rating.movie.title %>
</li>

app/views/ratings/create.js.erb
$('#trailer').empty().append("<%= j render @movie %>");
$('input[name="movie_id"]').val("<%= j @movie.id.to_s %>");
$("#title").text("<%= @movie.title %>");
$('input.btn').blur()

app/views/ratings/index.html.erb
<section>
    <div class="container text-center wow fadeIn">
        <h2>Movies to Whatch</h2>
        <hr class="colored">

        <div class="row content-row">
            <div class="col-lg-12">
                <div class="portfolio-filter">
                    <ul id="filters" class="clearfix"> 
                        <li>
                            <span class="filter active" data-filter="yes maybe">All</span>
                        </li>
                        <li>
                            <span class="filter" data-filter="yes">Yes</span>
                        </li>
                        <li>
                            <span class="filter" data-filter="maybe">Maybe</span>
                        </li>
                        <li>
                        <!-- id="showLeftPush" for push menu-->
                            <span id="showLeft">Genre</span>
                        </li>
                        <li>
                            <%= link_to button_tag("WhatchMe", id: "whatchMe"), lucky_path , target: "_blank" %>
                        </li>
                        <li>
                            <%= button_tag("EmailMe", id: "emailMe") %>
                        </li>
                    </ul>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-12">
                <div id="portfoliolist">
                    <%= render "posters" %>
                </div>
            </div>
        </div>
    </div>
</section>

<nav class="cbp-spmenu cbp-spmenu-vertical cbp-spmenu-left" id="cbp-spmenu-s1">
    <!-- Genres -->
    <% @genres.each do |genre| %>
        <a href="#"><span class="filter" data-filter="<%= genre.name %>"><%= genre.name %></span></a>
    <% end %> 
</nav>

<%= render 'listfooter' %>

app/views/ratings/temp.html.erb
<div id = "ratings">
	<h3>Yes!!</h3>
	<%= render 'list', :ratings => @ratings_yes %>

	<h3>Maybe</h3>
	<%= render 'list', :ratings => @ratings_maybe %>
</div>

app/views/ratings/update.js.erb
$('div[data-id="<%= j @rating.id.to_s %>"').fadeOut();
setTimeout(function() {
	$('div[data-id="<%= j @rating.id.to_s %>"').remove();
}, 1000);

app/views/users/email.js.erb
$('#email').val('').blur();